apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista
  namespace: argocd
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/nitheeshp-irl-microservice-helmcharts-AppofApps
    targetRevision: HEAD
    path: apps
  destination:
    server: https://7C0E0364DBF73CBBFA88A30E1DF0703E.gr7.us-east-2.eks.amazonaws.com
    namespace: argocd
  syncPolicy:
    automated: null