replicaCount: 1

image:
  repository: nitheesh86/microservice-frontend
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 30080

resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5